# Control loop frequency for the adapter thread
hz: 200
# Linux SocketCAN channel; bring up with: sudo ip link set can0 up type can bitrate 1000000
channel: can0
bitrate: 1000000
# Protocol: "sim" (safe default) or your real driver name (e.g., "rmd")
protocol: sim

# 12 joints in order: FR.hip, FR.thigh, FR.knee,  FL.hip, FL.thigh, FL.knee,
#                     RR.hip, RR.thigh, RR.knee,  RL.hip, RL.thigh, RL.knee
# Each joint maps to a motor id, with sign/zero/limits for conversion.
joints:
  - {id: 1,  sign: 1,  zero: 0.0, min: -1.6, max: 1.6}
  - {id: 2,  sign: 1,  zero: 0.0, min: -2.0, max: 2.0}
  - {id: 3,  sign: -1, zero: 0.0, min: -2.8, max: 0.0}

  - {id: 4,  sign: -1, zero: 0.0, min: -1.6, max: 1.6}
  - {id: 5,  sign: -1, zero: 0.0, min: -2.0, max: 2.0}
  - {id: 6,  sign: 1,  zero: 0.0, min: -2.8, max: 0.0}

  - {id: 7,  sign: 1,  zero: 0.0, min: -1.6, max: 1.6}
  - {id: 8,  sign: 1,  zero: 0.0, min: -2.0, max: 2.0}
  - {id: 9,  sign: -1, zero: 0.0, min: -2.8, max: 0.0}

  - {id: 10, sign: -1, zero: 0.0, min: -1.6, max: 1.6}
  - {id: 11, sign: -1, zero: 0.0, min: -2.0, max: 2.0}
  - {id: 12, sign: 1,  zero: 0.0, min: -2.8, max: 0.0}
